### ISSUE TITLE
self is not defined

### ISSUE THREAD

**Issue by adwerygaming** [lyswhut/lrc-file-parser#14]
Hello, I'm Trying To Use lrc-file-parser but it failed to run.
The Error Always Says: ReferenceError: self is not defined

> D:\GithubDesktop\distify13\node_modules\lrc-file-parser\dist\lrc-file-parser.js:16
> })(self, () => {
>    ^
> 
> ReferenceError: self is not defined
>    at Object.<anonymous> (D:\GithubDesktop\distify13\node_modules\lrc-file-parser\dist\lrc-file-parser.js:16:4)
>    at Module._compile (node:internal/modules/cjs/loader:1103:14)
>    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
>    at Module.load (node:internal/modules/cjs/loader:981:32)
>    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (D:\GithubDesktop\distify13\test\jsonToLRC\test.js:135:15)
>     at Module._compile (node:internal/modules/cjs/loader:1103:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)

The Error Refrence To This Line:
`const Lyric = require("lrc-file-parser")`

Code:
```
const Lyric = require("lrc-file-parser")
const filelrc = require("./lyric.lrc")
var lrc = new Lyric({
    onPlay: function (line, text) { // Listening play event
        console.log(line, text) // line is line number of current play
        // text is lyric text of current play line
    },
    onSetLyric: function (lines) { // listening lyrics seting event
        console.log(lines) // lines is array of all lyric text
    },
    offset: 0, // offset time(ms), default is 150 ms
    isRemoveBlankLine: true // is remove blank line, default is true
})

lrc.setLyric(filelrc) // set lyric, lyricStr is lyric file text, extendedLyricStrs is extended lyric file text array (optional)
// note: Setting the lyrics will automatically pause the lyrics playback
lrc.play(30000) // play lyric, 30000 is curent play time, unit: ms
```

LRC File:
```
[00:34.4]Mungkin sudah saatnya
[00:39.1]'Kan kuakhiri masa kesendirian
[00:46.4]Mempersiapkan hati 'tuk melamarmu
[00:55.6]Terimalah diriku
[01:06.3]Mungkin saat ini ku akan melepas masa lajangku
[01:15.2]'Kan kupersunting dirimu
[01:20.7]Jadilah pasanganku dan hidup menua bersamaku
[01:30.8]Terimalah cintaku
[01:38.3]♪
[01:41.4]Mungkin sudah saatnya
[01:46.2]'Kan kuakhiri masa kesendirian
[01:53.1]Mempersiapkan hati 'tuk melamarmu
[02:02.3]Terimalah cintaku, hu-uh-oh-oh
[02:13.5]Mungkin saat ini ku akan melepas masa lajangku
[02:22.4]'Kan kupersunting dirimu
[02:27.6]Jadilah pasanganku dan hidup menua bersamaku
[02:37.9]Terimalah cintaku
[02:43.8]Uh-oh-oh-oh, wo-wo-wo
[02:52.8]Wo-uh-hu-uh
[02:55.5]Mungkin saat ini ku akan melepas masa lajangku
[03:04.6]'Kan kupersunting dirimu
[03:09.5]Jadilah pasanganku dan hidup menua bersamaku
[03:22.8]Oh, mungkin saat ini ku akan melepas masa lajangku
[03:32.9]'Kan kupersunting dirimu
[03:37.9]Jadilah pasanganku dan hidup menua bersamaku
[03:48.3]Terimalah cintaku
[03:58.2]
```

**Comment by lyswhut** [comment]
This lib is designed to run in the browser, currently it is not supported to run in the node.js environment.
For what reason do you need to run in a node.js environment?

**Comment by adwerygaming** [comment]
> 

Ohh, Okay. Sorry. I Need it For My Discord Music Bot. Thanks!
